version: "3"
services:
  app:
    build:
      context: "docker/app/"
    ports:
      - 8093:80
    volumes:
      - "./public/:/var/www/html"
      - "./docker/app/httpd.conf:/etc/httpd/conf/httpd.conf"
    depends_on:
      - mysql
  mysql:
    build:
      context: "docker/mysql/"
    environment:
      - MYSQL_DATABASE=sampledb
      - MYSQL_HOST=localhost
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=mypassword
    volumes:
      - "storage:/var/lib/mysql"
      - "./docker/mysql/initdb/:/docker-entrypoint-initdb.d"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8094:80
    environment:
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=mypassword
    depends_on:
      - mysql
volumes:
  storage:
